mozilla-services/tecken

- bin/test
- circle.yml
> ci: fix DOCKER_DEPLOY var in circle.yml, fix creating .env file

- circle.yml
> docker deploy correctly

- tecken/symbolicate/views.py
- tests/test_symbolicate.py
Signed-off-by: Peter Bengtsson <mail@peterbe.com>
> only lookup cache once per symbol

- bin/run
> Use $CMD_PREFIX to conditionally enable New Relic

- .gitignore
- Makefile
- docker-compose.yml
- tests/systemtest/Dockerfile
- tests/systemtest/pytest.ini
- tests/systemtest/requirements.txt
- tests/systemtest/run_tests.sh
@willkg care to throw a quick eye on this?
By the way, thanks for all the tips! Especially about that nifty `-m venv` trick!
> Bug 1365235 separate systemtest python from regular python

- tecken/symbolicate/views.py
- tests/test_symbolicate.py
The "cause" was that, for the first time, we had stacks that point to modules in a "go back to previous" kind of order. E.g.
```
memoryMap: foo.pdb, bar.pdb
stacks (simplified): [0, addrX], [1, addrY], [0, addrZ]
```
There's nothing wrong with that format but it caused a bug in my code that was never noticed before and it was subtle. 
It loops over all the modules and sets up a `dict` for each one. But that initialization is cached so you don't have to do it for `foo.pdb` twice (because it's repeated in the list of stacks). 
The problem was that in the loop it also wrote down a complete list of all the offsets that need to be looked up in the Redis store. When it did that it would construct the key from the module name incorrectly. 
It would do this:
```python
for (index, module_name) in …
```
> KeyError on first load with mixed order of modules, fixes #948 #947

- tecken/symbolicate/views.py
- tests/test_symbolicate.py
> Optimize symbol parsing

- .circleci/config.yml
> Use ubuntu 18.04 in CircleCI

- .circleci/config.yml
> run CI linting as simple step

- .circleci/config.yml
> Use docker_layer_caching in CircleCI

- frontend/src/Users.js
> Filter inactive users

- tecken/base/symboldownloader.py
> Track amount of data downloaded from S3

- tecken/upload/tasks.py
- tests/test_upload.py
> Timer on update_uploads_created_task

- .circleci/config.yml
> use mozilla/cidockerbases:docker-latest

- .pyup.yml
> .pyup.yml syntax

- requirements.txt
- tecken/settings.py
- tecken/views.py
> Don't store results of Celery tasks

- requirements.txt
> AttributeError in Kombu

- frontend/src/Tokens.js
- tecken/api/forms.py
- tecken/api/urls.py
- tecken/api/views.py
- tests/test_api.py
> Ability to extend an API token

- docs/configuration.rst
- docs/dev.rst
- tecken/settings.py
- tests/test_views.py
> ignore exceptions on caches.default

- .circleci/config.yml
- bin/run.sh
> Frontend linting takes 1min CI every time

- Dockerfile
- frontend/Dockerfile
> Upgrade to latest Node LTS

- tecken/api/views.py
> UnboundLocalError in /api/uploads/

- frontend/src/Home.js
- tecken/api/views.py
> Use UploadsCreated in uploads api aggregates

- tecken/api/views.py
- tests/test_api.py
> use UploadsCreated for aggregates for superusers

- tecken/api/views.py
- tests/test_useradmin.py
> Metrics on API endpoints

- tecken/api/views.py
> one timing metrics key for app api endpoints

- tecken/api/views.py
- tests/test_api.py
> display of email in uploads ui

- .env-dist
- docs/configuration.rst
- docs/dev.rst
- frontend/src/Common.js
- tecken/s3.py
- tecken/settings.py
> Call it GOOGLE_APPLICATION_CREDENTIALS

- frontend/package.json
- frontend/src/Symbolication.js
- frontend/yarn.lock
> Use react-copy-to-clipboard on Symbolication app

- bin/build_frontend.sh
> Don't inline scripts in frontend

- docs/celery.rst
- frontend/src/Files.js
- frontend/src/Help.js
- frontend/src/Home.js
- frontend/src/Uploads.js
- tecken/apps.py
- tecken/base/symboldownloader.py
- tecken/base/utils.py
- tecken/benchmarking/views.py
- tecken/dockerflow_extra.py
- tecken/download/models.py
- tecken/download/tasks.py
- tecken/download/views.py
- tecken/settings.py
- tecken/storage.py
- tecken/upload/utils.py
- tecken/upload/views.py
- tests/test_dockerflow_extra.py
- tests/test_storage.py
- tests/test_symboldownloader.py
- tests/test_upload.py
> Name "S3" things more generically

- frontend/src/Files.js
- frontend/src/Uploads.js
> Changing filters should not show existing uploads whilst loading

- frontend/src/Home.js
- tecken/api/views.py
> "Last 30 days" stats on dashboard instead

- tecken/settings.py
> Redis TimeoutError on download should be swallowed

- tecken/symbolicate/views.py
- tests/test_symbolicate.py
> incorrect module name after an unknown module

- frontend/src/UploadNow.js
- tecken/api/urls.py
- tecken/api/views.py
- tecken/upload/views.py
- tests/test_api.py
- tests/test_upload.py
> Make it possible to webui-upload *private* symbols

- frontend/src/DownloadsMissing.js
- tecken/api/views.py
- tecken/download/models.py
- tecken/download/utils.py
- tests/test_api.py
- tests/test_download.py
> redis count of missing downloads count

- tecken/api/views.py
- tests/test_api.py
> cache missing downloads counts on home page

- frontend/src/Symbolication.js
> Symbolication stats only for authenticated users

- frontend/src/Common.js
- frontend/src/Tokens.js
- frontend/src/Upload.js
> date-fns no longer accepts strings

- docs/dev.rst
These aren't great, but it's a start.
> Add webapp test docs

- docs/benchmarking.rst
Pretty sure this finishes that section sufficiently.
Fixes #1695.
> Finish unfinished paragraph in benchmarking docs

- .env-dist
- Makefile
- bin/db.py
- bin/run.sh
- bin/setup-services.sh
- docs/dev.rst
- pytest.ini
- tecken/settings.py
This adds "make setup". It only sets up the db at the moment. We should add S3 and GCS, but I think we can do that in future PRs.
> bug 1556775: add "make setup"

- README.rst
This fixes the shields in the README so they're less clunky.
> Fix shields in README

- Dockerfile
> Update python to 3.7.5

- requirements.txt
https://docs.djangoproject.com/en/2.2/releases/2.1.14/
> Update to django 2.1.14

- .circleci/config.yml
- .env-dist
- Makefile
- bin/run.sh
- docker-compose.yml
- docs/dev.rst
- pytest.ini
- tecken/settings.py
This is some minor cleanup of project scaffolding: make, docker-compose.yml, and lint rules. This makes Tecken a little more like Socorro and friends.
> minor cleanup of scaffolding

- .circleci/config.yml
prettier is getting run in a different way in circle than it is in the local dev environment. That's causing problems when I upgrade prettier.
> Fix prettier run in circleci

- frontend/src/App.js
- frontend/src/File.js
- frontend/src/Files.js
- frontend/src/Home.js
- frontend/src/Symbolication.js
- frontend/src/Tokens.js
- frontend/src/Upload.js
- frontend/src/UploadNow.js
- frontend/src/Uploads.js
- frontend/src/User.js
- frontend/src/Users.js
The credentials argument defaults to "same-origin" now, so we don't need
to specify it.
> bug 1552947: remove credentials argument

- bin/db.py
- bin/delete-random-miniofiles.py
- bin/list-all-metrics-keys.py
- bin/run.sh
- bin/s3.py
- bin/sanspreamble.py
- bin/setup-services.sh
- docker-compose.yml
- tecken/apps.py
To test:
1. `make build`
2. `make setup`
3. `make test`
4. `make run`
> bug 1556775: add S3 bucket creation to "make setup"

- systemtests/bin/make-stacks.py
This fixes `make-stacks` to handle unknown frames and modules correctly.
To test:
1. `make shell`
2. `cd systemtests/`
3. `./bin/make-stacks.py save stackdir CRASHID` for a bunch of crash reports
> bug 1634372: fix make-stacks to handle unknown frames

- docs/download.rst
This file was mostly fine, so this is a mild update.
> bug 1657434: update download docs

- frontend/yarn.lock
This updates node-forge to 0.10.0 and a bunch of other dependencies to
current versions.
> Update js dependencies in yarn.lock

- tests/test_download.py
I inadvertently hard-coded the expected dates in the tests. This fixes
that.
> bug 1665692: fix tests

- frontend/src/Home.js
- tecken/api/urls.py
- tecken/api/views.py
- tecken/apps.py
- tecken/base/admin.py
- tecken/base/admin_site.py
- tecken/base/admin_urls.py
- tecken/base/templates/admin/site_status.html
- tecken/base/templates/admin/tecken_admin_index.html
- tecken/settings.py
- tecken/urls.py
- tests/test_api.py
This adds a status page to the Django admin. In order to do that, I had to add the ability to have static pages in the Django admin.
> bug 1667213: add status page to django admin

- tecken/base/admin.py
- tecken/base/templates/admin/site_status.html
Table counts will make it easier to see growth of data in the db.
> bug 1667132: add table counts to site status admin

- docker/Dockerfile
- requirements.in
- requirements.txt
Update Python to 3.9.2 and Django to 2.2.19.
> Update Python and Django

- tecken/symbolicate/views.py
Over the weekend, we had something hit the symbolication API and kick up
5,000 of these "ResponseError: WRONGTYPE Operation against a key holding
the wrong kind of value" errors.
We're replacing that code with Eliot at some point. This is a stop-gap
solution so it doesn't page us anymore. I'm setting the length to 0
which puts it in a "the keys exist, but the hashmap doesn't" situation
and I think the code will figure itself out from there.
> bug 1698371: stop-gap fix for ResponseError: WRONGTYPE

- setup.cfg
I want to start doing deploy bugs for Tecken, so this adds that
information to the release config.
> Update release config to set bugzilla product/component

- docs/configuration.rst
- eliot-service/eliot/app.py
- eliot-service/eliot/cache_manager.py
- eliot-service/eliot/liblogging.py
- requirements.in
- requirements.txt
This cleans up Eliot configuration and removes an intermediary (and
awkwardly used) AppConfig.
> bug 1727082: redo Eliot configuration

- eliot-service/eliot/app.py
- eliot-service/eliot/libsentry.py
The purpose of `/__broken__` is to help us test Sentry connectivity and also test uncaught error handling. However, Falcon changed how uncaught error handling works in 3.0.0 and we needed to update Eliot to work with that. This fixes the handling so that it works with Falcon 3.
> bug 1730950: fix /__broken__ so it sends errors to sentry

- eliot-service/eliot/cache_manager.py
This adds exception notification to the event handling loop. If there
are unhandled exceptions, they'll get sent to Sentry. It's possible the
unhandled exception is not ephemeral, so this keeps track of how many
errors of this kind it's hit and terminates if there are too many. I
don't know if 10 is a magic number, but seems like a good starting point
for a disk cache manager.
This also adds exception handling to shutdown when it's removing inotify
watches.
> bug 1699776: add exception notification to loop and shutdown

- docs/overview.rst
This updates the overview docs in regards to Eliot and also adds a rough
repository overview.
> bug 1728156: update overview docs

- eliot-service/eliot/symbolicate_resource.py
- eliot-service/tests/test_symbolicate_resource.py
This adds support for the Debug header in the symbolication API rewrite
for the v5 version. I predict we'll want to add other stats, so this
implements a flexible infrastructure for adding more stats without
having to pass anything else around.
Note that this doesn't add support for the Debug header for the v4 API
since that's deprecated and going away.
> bug 1734641: add debug stats to symbolication v5

- eliot-service/eliot/static/index.html
* fixes Python comments in example
* fixes CSS so navbar and page width look better across different device
widths
> Fixes Eliot index page

- eliot-service/eliot/static/index.html
* makes the page a little wider with a wide screen
* tweaks the code changing the indentation and adding comments
* removes redundant API docs link
> Tweak index page text and layout

- tecken/upload/management/commands/cleanse_upload.py
Because FileUpload has `on_delete=SET_NULL`, when we delete Upload from the db, it does a SELECT for all the Upload so it can update all the FileUpload. That's a ridiculous amount of data and when cleaning our stage/prod databases, it makes it impossible to run the command.
This (ab)uses a private method `_raw_delete()` to delete the data without doing the SELECTs. I think this should work going forward--Django 4.0 still has it.
This also prints the queries that run so we can more easily use/debug this going forward.
> bug 1749309: rework cleanse_upload to skip SELECTs

- tecken/settings.py
`get_version()` returns a dict, but we really want a friendly version
identifier for sentry errors. This fixes the code to pick version or
commit for that.
> bug 1671188: fix release value for sentry-sdk

- tecken/api/forms.py
- tecken/tests/test_api.py
This redos the size form field validation so it's a bit stricter in how
size blocks are composed.
> bug 1670918: redo size form field validation

- tecken/api/forms.py
This fixes another size validation bug with matching. This also fixes
the count validation in a similar way.
> bug 1670918: fix more size and count validation bugs

- eliot-service/eliot/app.py
- eliot-service/tests/test_cache_manager.py
- eliot-service/tests/test_libdockerflow.py
- eliot-service/tests/test_sentry.py
- tecken/apps.py
- tecken/tests/test_libdockerflow.py
- tecken/tests/test_sentry.py
Add libdockerflow tests, align Sentry event scrubbing with the plan, and switch from FalconIntegration (which isn't working) to SentryWsgiMiddleware.
> bug 1764569: fix minor sentry event scrubbing issues

- bin/debug-sym-file.py
- bin/download-sym.py
- bin/upload-sym.py
This adds three scripts that make it easier to automate sym file debugging and fixing.
> bug 1794095: add sym file manipulation scripts

- systemtests/bin/download-missing-symbols.py
- systemtests/bin/download-sym-files.py
- systemtests/bin/list-firefox-symbols-zips.py
- systemtests/bin/make-stacks.py
- systemtests/bin/symbolicate.py
- systemtests/bin/upload-symbols-by-download.py
- systemtests/bin/upload-symbols.py
This changes string interpolation and in some cases makes the output clearer for systemtests scripts.
> Improve systemtests scripts

- systemtests/bin/list-firefox-symbols-zips.py
- systemtests/bin/make-stacks.py
- tecken/tests/test_database.py
This switches some more %s interpolation to f-strings.
> Switch to f-strings

- bin/debug-sym-file.py
Changes debug-sym-file.py to print the entire sym file header including INFO lines.
Adds timing metrics for parsing into symcache.
> Improve debug-sym-file.py

- bin/delete-random-localstackfiles.py
- bin/run_lint.sh
- eliot-service/eliot/app.py
- eliot-service/eliot/cache.py
- eliot-service/eliot/cache_manager.py
- eliot-service/eliot/downloader.py
- eliot-service/eliot/liblogging.py
- eliot-service/eliot/libsymbolic.py
- eliot-service/eliot/symbolicate_resource.py
- pyproject.toml
- requirements.in
- requirements.txt
- setup.cfg
- systemtests/bin/make-symbols-zip.py
- tecken/api/forms.py
- tecken/base/form_utils.py
- tecken/download/forms.py
- tecken/download/utils.py
- tecken/storage.py
- tecken/tests/test_download.py
- tecken/tests/test_upload.py
- tecken/tokens/middleware.py
- tecken/upload/forms.py
- tecken/upload/management/commands/remove_orphaned_files.py
- tecken/upload/views.py
This switches from flake8 to ruff. It also fixes a series of bugbear issues raised by ruff.
> Bug 1823914: switch to ruff

- requirements.in
- requirements.txt
* datadog: 0.44.0 -> 0.45.0
* markus: 4.1.0 -> 4.2.0
* symbolic: 12.1.0 -> 12.1.2
* urllib3: 1.26.14 -> 1.26.15
> Updates 20230418

- requirements.in
- requirements.txt
* boto3: 1.26.125 --> 1.26.127
* botocore: 1.29.125 --> 1.29.127
* sentry-sdk: 1.21.1 --> 1.22.1
> Updates 20230505

- tecken/upload/admin.py
- tecken/upload/models.py
This makes it possible to edit data in the future.
This also improves the models in regards to Django best practices.
> bug 1746940: add FileUploadAdmin and UploadAdmin to Django admin

- bin/upload-sym.py
- tecken/download/views.py
- bug 1746940: remove errant logging.info line
- bug 1746940: fix upload-sym file for Windows modules
> bug 1746940: minor fixes

- tecken/api/views.py
- tecken/download/views.py
- tecken/tests/test_download.py
This re-implements the codeinfo lookup in the download API which kicks in if a symbol file wasn't found and if the debugfilename/debugid look like a possible codefile/codeid.
> bug 1746940: implement codeinfo lookup in download API

- .github/dependabot.yml
This cleans up the yaml for the configuration file and disables automatic rebasing.
> Disable dependabot auto-rebasing

- bin/circleci_push.sh
This is the same change as https://github.com/mozilla-services/antenna/pull/947, but for Tecken.
> bug 1860576: Make Docker Hub upload script more robust.

- tecken/api/forms.py
- tecken/api/views.py
- tecken/base/symboldownloader.py
- tecken/storage.py
- tecken/upload/models.py
This removes some random unused code I encountered while reading the code. This isn't the result of any kind of systematic survey, so there's probably more unused code.
> Remove unused code.

- bin/gcs_cli.py
- docker-compose.yml
- docker/config/local_dev.env
and other updates to match https://github.com/mozilla-services/antenna/pull/976
> use http for gcs-emulator

- docker/Dockerfile
- frontend/Dockerfile
See #mozilla-services/socorro-stackwalk/pull/15
> specify platform in base image

- bin/run_web_disk_manager.sh
the timeout occurred again, as discussed doubling the timeout again
> bug-1873752: double remove_orphaned_files timeout again

- tecken/api/views.py
- tecken/base/symbolstorage.py
- tecken/download/views.py
- tecken/ext/__init__.py
- tecken/ext/s3/__init__.py
- tecken/ext/s3/storage.py
- tecken/libdockerflow.py
- tecken/libstorage.py
- tecken/settings.py
- tecken/tests/test_api.py
- tecken/tests/test_download.py
- tecken/tests/test_libdockerflow.py
- tecken/tests/test_s3_storage.py
- tecken/tests/test_symbolstorage.py
- tecken/tests/test_upload.py
- tecken/tests/test_upload_utils.py
- tecken/upload/models.py
- tecken/upload/utils.py
- tecken/upload/views.py
This PR defines a storage interface, so we can support both S3 and GCS in Tecken. In this PR I only included the implementation for S3.
> bug-1564452: Define a storage interface and implement it for S3

- .github/workflows/build-and-push.yml
> OBS-268: Fix workflow syntax.

- systemtests/README.rst
- systemtests/test_env.py
I refactored the code a bit as well.
* The information about the different environments is now data rather than code.
* I simplified iterating of the list of zip files a bit.
> bug-1908689: Allow running systemtests against the new GCP environments.

- tecken/settings.py
I forgot the S3 region in #2957.
> bug-1827506: Add setting to configure the S3 region in AWS.

- requirements.in
- requirements.txt
This picks up some security fixes.
https://mozilla-hub.atlassian.net/browse/OBS-333
> OBS-333: Upgrade Django to version 4.2.16.

- systemtests/README.rst
- systemtests/lib/fake_data.py
- systemtests/lib/tecken_client.py
This addresses the action items related to documentation in https://github.com/mozilla-services/tecken/pull/2974#issuecomment-2258475812.
> bug-1909870: Improve system tests documentation.

- bin/run_web.sh
- bin/stop_gunicorn.sh
https://mozilla-hub.atlassian.net/browse/OBS-410
> OBS-410: Add script for graceful gunicorn shutdown.

- bin/stop_gunicorn.sh
https://mozilla-hub.atlassian.net/browse/OBS-460
> OBS-460: Increase pod shutdown delay.

- .devcontainer/Dockerfile
- docker/Dockerfile
https://mozilla-hub.atlassian.net/browse/OBS-270
> OBS-270: Use Python images based on Debian bookworm.

- .readthedocs.yaml
While doing this, I'm updating the OS used to build docs.
> obs-530: fix readthedocs configuration

- .github/workflows/build-and-push.yml
This is the same change as in https://github.com/mozilla-services/antenna/pull/1273.
https://mozilla-hub.atlassian.net/browse/CRINGE-65
> CRINGE-65: Upgrade to version 4 of the docker-push action.
