- tecken/apps.py
To be merged, by miles, after this has worked once:
```
curl -d '{"stacks":[[[0,11723767],[1, 65802]]],"memoryMap":[["xul.pdb","44E4EC8C2F41492B9369D6B9A059577C2"],["wntdll.pdb","D74F79EB1F8D4A45ABCD2F476CCABACC2"]],"version":4}' https://symbols.dev.mozaws.net
```
> undo temp flushall

- Makefile
- bin/cp-env-file.sh
This copies the .env-dist file over if .env doesn't exist. It also adds a header
indicating which .env-dist got copied which is helpful sometimes.
r?
> Fixes bug 1370960 - Copy .env-dist if .env doesn't exist

- .gitignore
- bin/list-all-metrics-keys.py
- bin/run.sh
- docs/dev.rst
- tecken/markus_extra.py
- tecken/settings.py
This'll make it easier to get an insight into what ALL keys are being used. Using its output you can make sure they're all used in Datadog in some form.
> bug 1364937 - log all metrics keys used

- bin/run.sh
The default is 30s. So not only does this make it configurable, it also changes the default to 60 seconds.
> bug 1399140 - longer gunicorn timeout

- bin/test.sh
- docker-compose.yml
- pytest.ini
@milescrabill I think I figured it out. At least it all makes sense locally. 
If you run `docker-compose run test-ci test` it runs the `test-ci` directive from `docker-compose.yml`. So, that'll run with the files "as of the latest `make build`". 
To test this, I do:
```
$ export CI=true
$ make test
```
The tests pass. So I mess with, for example, `tests/test_api.py` and put in a `raise Exception("hi")` and run: `make test` again and the tests pass again. 
However, when I do this WITHOUT setting `export CI=true` the tests will re-read the host's file and the second time the tests fail because of the temporary `raise Exception("hi")` I put in.
> only volume mount explicitly

- .circleci/config.yml
per https://circleci.com/docs/2.0/configuration-reference/#tags and https://circleci.com/docs/2.0/workflows/#git-tag-job-execution we need to whitelist which jobs run in our workflow in the case of pushing a tag.
this is why we weren't seeing builds for tag jobs earlier.
i've tested this using the following repo that seeks to mirror tecken (and other mozilla projects') structure:
https://github.com/mozilla-services/ci-testground
see release here: https://github.com/mozilla-services/ci-testground/releases/tag/v0.1.1
corresponding workflow build here: https://circleci.com/workflow-run/53225b01-935b-4167-856a-f6cdd5676cad
corresponding tagged docker image: https://hub.docker.com/r/mozilla/testground/tags/
> circle config: add tag specifiers for all workflow jobs

- tecken/symbolicate/views.py
- tests/test_symbolicate.py
@luser The code kinda speaks for itself. I just made it so that the symbolication works with *and without* the 'm' after 'FUNC' and 'PUBLIC'. 
Left a code comment in there to note that some day we might actually use the 'm' in the symbolication.
> optional 'm' after FUNC or PUBLIC, fixes #924

- docs/dev.rst
This also removes the section on Grafana and Graphite. Markus can log metrics
and that's more helpful in a local dev environment.
> Add test plan

- .env-dist
- docker-compose.yml
- docker/images/oidcprovider/Dockerfile
- docker/images/oidcprovider/fixtures.json
- docs/authentication.rst
- docs/configuration.rst
- docs/dev.rst
- tecken/settings.py
Use testprovider from [mozilla-parsys/docker-test-mozilla-django-oidc](https://github.com/mozilla-parsys/docker-test-mozilla-django-oidc) for authentication in the local development environment.
You may need to comment out ``DJANGO_OIDC_RP_CLIENT_ID`` and other parameters in your ``.env``, to get the new defaults.  Restart with ``make build run``, go to ``http://localhost:3000``, and authenticate. The setup is very similar to Socorro.
The docs are updated to reflect the new default, and that extra steps are required beyond the client ID and secret to get Auth0 working now.
> bug 1552901: Use oidcprovider in local dev

- .env-dist
- Makefile
- docker-compose.yml
- docs/dev.rst
- tecken/apps.py
- tecken/download/views.py
- tecken/storage.py
- tests/test_dockerflow_extra.py
- tests/test_storage.py
- tests/test_upload.py
**This is work in progress**, to preview my approach so far. Feel free to ignore or give feedback here or on [bug 1552950](https://bugzilla.mozilla.org/show_bug.cgi?id=1552950). This PR will probably not be the one submitted for review.
Add ``gcs-emulator``, an emulator for Google Cloud Storage, analogous to ``minio`` for AWS S3.
* Create the bucket during startup
* Upload symbols from a .zip, create file records
* Make interfaces on ``StorageBucket`` to handle differences between S3 and GCS, and real and emulated services, rather than handling differences in the client code. For example, currently to check if the bucket defined in ``DJANGO_UPLOAD_DEFAULT_URL`` exists:
```
from botocore.exceptions import ClientError
from google.cloud.exceptions import NotFound
from tecken.storage import …
```
> bug 1552950: Add GCS Emulator

- tecken/apps.py
- tecken/dockerflow_extra.py
- tecken/download/views.py
- tecken/storage.py
- tecken/upload/utils.py
- tecken/upload/views.py
- tests/test_dockerflow_extra.py
- tests/test_storage.py
- tests/test_upload.py
This PR, part of [bug 1564452](https://bugzilla.mozilla.org/show_bug.cgi?id=1564452), adds some methods to ``StorageBucket`` so that client code can use object storage without being as concerned whether it is S3 or GCS, emulated or "real".
* ``exists()``: Returns ``True`` if the bucket exists, ``False`` if it does not, and raises a backend-specific exception for issues like authentication and authorization issues.
* ``backend()``: Set to a string like ``"s3"`` or ``"emulated-gcs"``, to classify the backend if needed.
This expands the code and tests in ``StorageBucket``, and simplifies the code and tests for the code that checks for bucket existence.
This first PR took more time than I planned, as I got my S3 and GCS accounts setup, and made a bunch of test requests to investigate the API, …
> bug 1564452: Add StorageBucket.exists(), .backend()

- Dockerfile
This pins to Python 3.7.4 using slim and stretch. We need to keep using
stretch because it has the gcc-6 package which we need to compile
`dump_syms`. In order to get off of stretch, we'd need to fix all that.
It's probably doable, but I didn't want to tackle it today.
> Upgrade to Python 3.7

- docker-compose.yml
Switch from the test Docker image to [fsouza/fake-gcs-server](https://hub.docker.com/r/fsouza/fake-gcs-server), which is maintained by the [upstream project](https://github.com/fsouza/fake-gcs-server/), and is configured via the command line instead of environment variables.
As documented, to switch to the GCS emulator, override the URLs in the ``.env`` file:
```
DJANGO_SYMBOL_URLS=https://gcs-emulator.127.0.0.1.nip.io:4443/tecken
DJANGO_UPLOAD_DEFAULT_URL=https://gcs-emulator.127.0.0.1.nip.io:4443/tecken
```
I was able to upload a symbols .zip with the new server.
> bug 1563036: Switch to official gcs emulator image

- frontend/src/Uploads.js
The page was failing with a RangeError because of the Z. This fixes that.
```
08:49:24.557 RangeError: "Format string contains an unescaped latin alphabet character `Z`"
F index.js:422
F index.js:395
render Uploads.js:431
React 11
_fetchUploads Uploads.js:108
promise callback*be/this._fetchUploads/< Uploads.js:107
promise callback*be/this._fetchUploads Uploads.js:90
componentDidMount Uploads.js:68
React 3
unstable_runWithPriority scheduler.production.min.js:266
React 12
61 index.js:7
Webpack 6
console.js:39
```
`format()` comes from date-fns which renovate updated from 2.0.0-beta3 to 2.0.0-beta4. Pretty sure this broke then. I skimmed the changelog, but don't really know this library so I'm not sure what caused it to break.
> Fix uploads page

- frontend/src/Uploads.js
This is a fix to 3470baa8. In that, I removed the Z altogether, but the
Z needs to be there as a Z--not a formatting symbol. This re-adds it, but
escaped.
> Re-add Z, but escape it

- frontend/src/Uploads.js
In date-fmt, ' is an "escape character", but "escaped" things actually
need to be quoted. This adds the end '.
> Fix uploads date-fmt format usage

- frontend/package.json
- frontend/src/Common.js
- frontend/yarn.lock
This updates a few things that GitHub said are security issues as well
as a few things "yarn audit" was sad about, too.
Update dependencies:
* date-fns 2.0.1 -> 2.1.0
* react-scripts 3.0.1 -> 3.1.1
Update resolution things:
* babel-eslint 10.0.1 -> 10.0.2
* braces 2.3.1 -> 3.0.2
* handlebars 4.0.13 -> 4.2.0
Add new resolution things:
* eslint-utils >= 1.4.1 (security issue)
* mixin-deep >= 2.0.1 (security issue)
* set-value >= 3.0.1 (security issue)
To test:
1. `make build`
2. `make setup`
3. `make lintcheck` to make sure there aren't linting issues
4. `make run` and then go to `localhost:3000` and click around
> Update js requirements

- docker/images/oidcprovider/Dockerfile
This only affects the local dev environment. Now that we have this, I can do this from the shell:
```
docker-compose exec oidcprovider /code/manage.py createuser USER PASSWORD EMAIL
```
> bug 1590767: update oidc-testprovider to v0.9.3

- tecken/settings.py
Taskcluster is moving to a new infrastructure. This adds two more
domains to the `ALLOW_UPLOAD_BY_DOWNLOAD_DOMAINS` setting allowing symbols
upload tasks to upload by download from the new infrastructure.
> bug 1592143: add new domains to ALLOW_UPLOAD_BY_DOWNLOAD_DOMAINS

- frontend/package.json
- frontend/yarn.lock
* react-scripts 3.2.0 → [3.3.0](https://github.com/facebook/create-react-app/blob/master/CHANGELOG.md): Minor release, supports custom templates, option chaining, and nullish coalescing operators.
TypeScript 3.7.0 or later is optional, but needed for new operators. Tecken doesn't use TypeScript, so we don't install it, and get this warning when installing:
```
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
```
Used `yarn upgrade --dev --latest react-scripts`, so many dependency updates as well.
Tested with:
```
docker-compose build frontend
make run # Wait for frontend to say "Compiled …
```
> Upgrade to react-scripts 3.3.0

- .circleci/config.yml
- .env-dist
- Makefile
- bin/build_frontend.sh
- docker/Dockerfile
- frontend/Dockerfile
This fixes permission issues when running the docker containers on Linux where the uid/gid of the host user doesn't match the app user.
To test:
1. add `USE_UID` and `USE_GID` to `.env`
2. `make build`
3. `make setup`
4. `make lintfix`
5. `make test`
6. `make run` (though this is broken because of a different issue that I'll get to next)
None of those should result in files that are owned by root or some other user.
> bug 1628802: fix permissions issues in docker containers

- frontend/Dockerfile
- frontend/bin/build_yarn_lock.sh
- frontend/package.json
- frontend/yarn.lock
This fixes the frontend container to run with the UID/GID set in the `.env` file so it doesn't create files as root.
This adds a script to build the yarn.lock file and dealing with the `frontend/node_modules/` directory that has "stuff" in it and can cause problems if left around.
This demotes react-scripts back to 3.4.0 which works--3.4.1 seems to skip running the dev server with no errors.
This rebuilds the `yarn.lock` file.
To test:
1. `make build`
2. `make run`
3. go to http://localhost:3000 and click through the site
> bug 1630120: fix frontend in local dev environment

- tecken/settings.py
I'm pretty sure static assets are served by whitenoise which is adding this header:
```
Access-Control-Allow-Origin: *
```
Since we're not hosting static assets on a CDN, we don't need this so we should disable it.
> bug 1596109: fix ACAO header with static assets

- systemtests/bin/download-missing-symbols.py
- systemtests/test_env.sh
This adds a test to make sure that `/missingsymbols.csv` is working.
> bug 1641212: add missingsymbols.csv systemtest

- requirements/default.txt
Redis deprecated HMSET. We're still using 3.4.2 in production. Redis 4 added variadic arguments to HSET which is what you're supposed to switch to. That's all super....
However, updating the Python redis library to 3.5.0 deprecates hmset so you have to switch to hset, but we can't use variadic arguments because the version of Redis we're using doesn't support it. Ergo, we're hosed.
We have a few of options:
1. Update Redis in stage/prod to something >= 4.
2. Rewrite the symbolicate API view code to not use hmset.
3. Pin the library to 3.4.1 and push this off until another day.
I'm choosing option 3 for now.
> Add note about redis==3.4.1

- frontend/yarn.lock
This rebuilds yarn.lock to pick up updates on a variety of libraries including a security fix in websocket-extensions (0.1.3 -> 0.1.4).
> Rebuild yarn.lock

- docs/conf.py
- docs/symbolication.rst
- requirements/docs.txt
This overhauls the symbolication API docs to make them more user-focused. It should be easier to read the docs and understand how to use the API now.
Further, this fixes the docs so they use the sphinx-rtd-theme when building locally. This is what we use on RTD, so it makes it easier to edit and author them locally.
> bug 1627052: rewrite symbolication API docs

- contribute.json
- docs/upload.rst
- frontend/src/Help.js
- frontend/src/Home.js
We created a Tecken product in Bugzilla and all Tecken bugs should get filed there. This updates the links accordingly.
> bug 1650917: update bugzilla links to Tecken product

- systemtests/bin/make-stacks.py
- tecken/symbolicate/views.py
- tests/test_symbolicate.py
This fixes symbolication to handle empty strings for the debug filename
and debug id in the memoryMap portion of the symbolication request.
Previously, it would raise an error. It no longer raises an error.
Instead, the code doesn't check cache and doesn't try to download the
module and treats it as if the module isn't available.
I also fixed make-stacks so it no longer drops modules where the debug
filename or id aren't known.
> bug 1649531: handle empty string debug filename and id

- tecken/api/views.py
- tecken/download/management/__init__.py
- tecken/download/management/commands/__init__.py
- tecken/download/management/commands/cleanse_missingsymbol.py
- tecken/download/models.py
- tecken/download/utils.py
- tests/test_api.py
- tests/test_download.py
This removes some code about total counts that we don't really need. This also adds a Django management command and test for removing old entries in the missingsymbol table.
To test:
1. run tests
2. create entries in missingsymbol and run `manage.py cleanse_missingsymbol`
> bug 1651190: maintain missingsymbol table

- tecken/upload/management/__init__.py
- tecken/upload/management/commands/__init__.py
- tecken/upload/management/commands/cleanse_upload.py
- tests/test_upload.py
This deletes `upload_upload` and `upload_fileupload` records for files that have expired in S3.
> bug 1638412: add cleanse_upload command

- systemtests/bin/list-firefox-symbols-zips.py
- systemtests/bin/upload-symbols-by-download.py
- systemtests/bin/upload-symbols.py
- systemtests/test_env.sh
- tecken/tokens/middleware.py
This fixes the issue where the client is trying to upload a big symbols file using a bad token. The Tecken middleware will see the auth header, recognize it's a bad token, and then return a 403 with some message. However, if the client is using chunked transfer encoding and the request body hasn't been fully sent, the connection gets dropped before the client gets the 403 response.
This fixes that by forcing the middleware to slurp the entire request body (if possible) before sending the 403 response.
This adds a system test that tests the situation in stage and prod environments.
To test:
1. run tests to make sure they still pass
2. run the system test against the stage environment to verify it fails in the "UPLOAD WITH BAD TOKEN TEST--this should return a 403 and error and not a …
> bug 1655944: fix bad token responses so the client gets them

- systemtests/test_env.sh
- tecken/tokens/middleware.py
In a chunked transfer encoding scenario, the content length will be 0
so using that to guard against reading forever won't work. Underneath
the Django request .read() is gunicorn's read which will handle
dropped connections, timeouts, and other possible data transfer issues.
Given that, we can just loop until there's nothing left to read and
that'll be ok.
> bug 1655944: fix force_full_request_body_read function

- docs/symbolication.rst
- docs/upload.rst
This improves the upload documentation to make it easier for people who
are using the upload API to implement their clients. This documents the
various status codes and what the client should do when it encounters
them.
This slims down some of the explanatory text that isn't particularly
helpful and clarifies some of the text around what decisions an upload
client needs to make.
> bug 1656313: update upload docs

- docs/dev.rst
- docs/download.rst
- docs/endtoendtesting.rst
- docs/symbolication.rst
- docs/upload.rst
- frontend/src/APIRequests.js
- frontend/src/Symbolication.js
We really want people to specify the User-Agent HTTP header so we can
better know who we need to talk to when changing API things.
> bug 1665127: add notes about user-agent

- docs/download.rst
- docs/symbolication.rst
- tecken/api/forms.py
- tecken/api/views.py
- tecken/base/form_utils.py
- tecken/download/forms.py
- tecken/download/urls.py
- tecken/download/views.py
- tecken/settings.py
- tests/conftest.py
- tests/test_download.py
- tests/test_upload.py
- tests/test_views.py
Previously, we had a `/missingsymbols.csv` endpoint which returned missing symbol data from yesterday as a CSV.
This adds a `/missingsymbols/` endpoint which lets you query missing symbol data.
This is a first-pass to get something on stage that Gabriele can test out to see if it meets his needs.
This needs:
1. a systemtest because it's officially supported
2. documentation
I'll probably do item 2 in this PR.
> bug 1665692: add missingsymbols endpoint

- bin/test.sh
The tests are kicking off before the backing services have started up.
What we should really be doing is using urlwait or something like that
which will cause everything to pause while the service is coming up, but
because of the way configuration works, we may not have the service urls
in the environment so we'll have to go with this "start it up a little
bit before" method for now.
> bug 1667213: reduce race condition between tests and services

- systemtests/bin/symbolicate.py
- systemtests/data/sym_files_to_download.csv
This improves the error message for a user when the stack to be
symbolicated isn't valid JSON.
This fixes the comment in the `sym_files_to_download.csv` to be
correct--the response HTTP status code doesn't have anything to do with
tokens.
> Fixes to systemtests

- docs/upload.rst
- tecken/upload/views.py
If the specified url in an upload-by-download request can't be downloaded, the `UploadByDownloadForm` will probably catch it when it does a HEAD request. It's vaguely possible that if the HEAD succeeds, the following GET might fail.
This adds some minor handling in the case where the HEAD succeeds and the GET fails. It returns an HTTP 400 telling the user the error. The user should check the download works and retry.
> bug 1669498: handle upload-by-download download url failure

- bin/entrypoint.sh
- tecken/base/symboldownloader.py
- tecken/base/utils.py
- tecken/requests_extra.py
- tecken/upload/forms.py
- tecken/upload/views.py
- tecken/useradmin/management/commands/is-blocked-in-auth0.py
- tecken/useradmin/middleware.py
The requests library defaults to an infinite timeout, so it's possible that a request could cause a Python process to hang forever. That's super bad for Tecken, so this fixes requests uses to always have a default timeout and always retry.
> bug 1669519: always set a timeout when using requests

- .circleci/config.yml
This updates to a Docker version that's not being deprecated by
CircleCI.
> Update docker version in CircleCI config

- frontend/package.json
- frontend/yarn.lock
This gets us past a security vulnerability with object-path < 0.11.5.
This also updates mobx and mobx-react because yarn couldn't resolve the
pinned versions of those dependencies with other things and it seemed
easier to update the pinned versions than spend time to sort it all out.
> Update object-path to >=0.11.5

- eliot-service/eliot/libsentry.py
This fixes `setup_sentry_logging()` to only send Sentry alerts for ERROR
messages.
> bug 1677570: fix sentry logging

- docs/conf.py
- docs/dev.rst
- docs/exts/eliot_metrics.py
- eliot-service/eliot/cache.py
- eliot-service/eliot/cache_manager.py
- eliot-service/eliot/downloader.py
- eliot-service/eliot/libmarkus.py
- eliot-service/eliot/symbolicate_resource.py
- eliot-service/tests/test_symbolicate_resource.py
This reimplements how metrics work in Eliot and adds the ones we need
for the bug.
The new system centralizes all the metrics that Eliot generates into a
single file. It adds an extension for extracting that data and
auto-generating documentation. It also shapes the metrics data as a
Markus MetricsFilter so it validates any metrics being emitted.
Adding a new metric involves adding it to ELIOT_METRICS and then adding
the code to emit the metric. That's about how much effort it was before,
so I think this seems promising. I'm inclined to redo Tecken webapp
accordingly.
> bug 1674406: reimplement metrics in Eliot and add new ones

- eliot-service/eliot/libmarkus.py
- eliot-service/eliot/symbolicate_resource.py
This changes the gauge metrics for Eliot to histograms.
When doing that, I hit some issues and decided that logging a warning in
the local dev environment when metrics were wrong wasn't good enough--we
really want them to throw exceptions. So I tweaked that code so that
the filter only runs in local dev environment and tests and raises
exceptions.
> bug 1674406: change gauge to histogram

- requirements.in
- requirements.txt
This fixes the issue where pip-compile was using something in pip that
isn't there anymore and throwing a TypeError.
> Update pip-tools to 5.4.0

- frontend/src/Home.js
I moved user management to the Django admin, but missed the UsersTile
link to the old user management pages. This removes that entire tile.
Further, this removes the duplicate Authentication tile. We've got a
"Sign In" link in the upper right hand corner, so we don't additionally
need this.
> bug 1683665: remove UsersTile which had bad link

- docs/download.rst
The download API takes two additional querystring params that weren't
documented: `code_id` and `code_filename`.
These are in the HTTP requests from minidump-stackwalk in Socorro's
processor. I don't know what else uses these parameters.
> bug 1688623: add docs for code_id and code_filename

- docker/Dockerfile
- frontend/Dockerfile
- frontend/package.json
- frontend/yarn.lock
This updates node to 15.7.0-slim (for both Docker images) and updates react-scripts to 4.0.1. It also updates prettier, mobx, and mobx-react to current versions. Plus it rebuilds `yarn.lock`.
To test:
1. run `make run` which launches the dev frontend
2. click around and make sure the dev frontend is working
3. run `make lint` and `make lintfix` to make sure the new version of prettier doesn't have changes it wants to make
> bug 1672712: update react-scripts

- eliot-service/eliot/app.py
- eliot-service/eliot/cache.py
- eliot-service/eliot/cache_manager.py
- eliot-service/tests/conftest.py
- eliot-service/tests/test_cache_manager.py
This reworks things so everything is in the cache dir. This fixes the
possible problem where the `symbols_tmp_dir` and `symbols_cache_dir` are
different volumes which causes Eliot to error out when moving files
between the two paths.
> bug 1681632: rework things so everything is in the cachedir

- requirements.in
- tecken/cache_extra.py
- tecken/settings.py
Tecken had a MSGPackSerializer that fixed an issue in django-redis
preventing us from using recent releases of msgpack. django-redis
released a version (4.12.0) that supports recent releases of msgpack, so
we don't need our MSGPackSerializer anymore.
Note that we need to keep msgpack in requirements.in because we use the
MSGPackSerializer from django-redis and django-redis doesn't have
msgpack in an install extras kind of thing.
> bug 1701832: remove MSGPackSerializer

- eliot-service/eliot/cache.py
- eliot-service/eliot/symbolicate_resource.py
- eliot-service/tests/test_cache.py
- eliot-service/tests/test_symbolicate_resource.py
For Windows SYM files, the debug_filename is something.pdb, but we
really want to return something.dll which is the PE filename. SYM files
encode this in the INFO line.
symbolic parses that line and captures that information, but doesn't
make it available in the symcache, so we had to add some code to peek in
the SYM file and pull out the PE filename if it's there. But then since
we're caching symcache files on disk, we needed to redo disk caching to
cache items that consist of multiple key/val pairs.
This stores the key/val data as a single file using msgpack. That way
the disk cache LRU can think about files as units and we don't have to
deal with the complexities of other possibilities.
> bug 1699546: return correct value for "module" in symbolication

- eliot-service/eliot/symbolicate_resource.py
- eliot-service/tests/test_symbolicate_resource.py
This adds a "file" key to the symbolication output which has the source file in it.
> bug 1701653: add "file" to symbolication API output

- eliot-service/eliot/cache_manager.py
- eliot-service/eliot/libmarkus.py
- systemtests/bin/make-stacks.py
This fixes an issue in make-stacks.py that I hit while working on the disk cache evictions issue.
This also adds an `eliot.diskcache.usage` gauge so we can see how the disk cache grows over time.
> bug 1674406: measure disk cache usage

- eliot-service/eliot/cache.py
- eliot-service/eliot/symbolicate_resource.py
- eliot-service/tests/test_cache.py
If we check to see if the item is in the cache before doing cache.get(),
then we miss out on metrics generation for misses and errors.
Further, the previous code didn't handle errors when cache.get() has
problems.
> bug 1674406: fix cache hit/miss metrics generation

- requirements.in
Since we're using msgpack in Eliot now, we don't need the note about how
it's needed by django-redis.
> bug 1699546: remove note about msgpack

- frontend/yarn.lock
This updates hosted-git-info to 2.8.9 and other js dependencies that
haven't been updated in a while.
> Update js dependencies

- eliot-service/eliot/app.py
- eliot-service/tests/conftest.py
- eliot-service/tests/test_symbolicate_resource.py
- systemtests/bin/symbolicate.py
This uses the built-in Falcon CORSMiddleware to add the access control headers. This is slightly different than what the Tecken symbolication API does where it adds the headers regardless of whether it's a preflight request or not.
However, the origin and expose-headers values are the same, so I think this will work for the affected projects.
> bug 1713667: implement CORS access control headers

- docker/Dockerfile
- requirements.in
- requirements.txt
* Re-generate requirements.txt
* Bump sphinx from 4.0.2 to 4.1.0 (from PR #2379)
* Bump symbolic from 8.2.1 to 8.3.0 (from PR #2378)
* Bump node from 16.3.0-slim to 16.4.2-slim in /docker (from PR #2377)
* Bump python from 3.9.5-slim to 3.9.6-slim in /docker (from PR #2369)
> Updates 20210713 2

- eliot-service/eliot/app.py
- eliot-service/eliot/cache_manager.py
- eliot-service/eliot/liblogging.py
- eliot-service/eliot/libmarkus.py
- eliot-service/tests/conftest.py
- requirements.in
- requirements.txt
This updates Eliot to Everett 2.0.0 and reworks component configuration.
It also fixes `setup_metrics` and `setup_logging` so they're explicit about
what argument data is being used.
> bug 1722602: update to everett 2.0.0

- docker/Dockerfile
- frontend/yarn.lock
- requirements.in
- requirements.txt
* Recompile requirements.txt
* Bump tar from 6.1.0 to 6.1.3 in /frontend (from PR #2389)
* Bump python-dateutil from 2.8.1 to 2.8.2 (from PR #2388)
* Bump requests from 2.25.1 to 2.26.0 (from PR #2387)
* Bump pytest-mock from 3.6.0 to 3.6.1 (from PR #2386)
* Bump django-cache-memoize from 0.1.8 to 0.1.10 (from PR #2385)
* Bump mozilla-django-oidc from 1.2.4 to 2.0.0 (from PR #2384)
* Bump node from 16.4.2-slim to 16.6.0-slim in /docker (from PR #2383)
> Updates 20210804

- .log4brains.yml
- docs/_static/css/custom.css
- docs/adr/20210819-use-log4brains-to-manage-the-adrs.md
- docs/adr/20210819-use-markdown-architectural-decision-records.md
- docs/adr/20210820-symbolication-microservice.md
- docs/adr/README.md
- docs/adr/index.md
- docs/adr/template.md
- docs/adr_log.rst
- docs/conf.py
- docs/exts/adr_log.py
- docs/index.rst
This adds the scaffolding for creating and maintaining ADRs. It adds an
ADR log to readthedocs.
It adds an ADR for breaking out the symbolication API as a microservice.
> bug 1726652: add ADR scaffolding and symbolication microservice ADR

- eliot-service/eliot/symbolicate_resource.py
- eliot-service/tests/test_symbolicate_resource.py
If there's no file information for the symbol, then including a line
number doesn't make any sense. This changes the code to omit the line
number if there's no file information.
> bug 1701978: don't include line if there's no file

- docker/Dockerfile
- frontend/yarn.lock
- requirements.in
- requirements.txt
* Bump immer from 9.0.2 to 9.0.6 in /frontend (from PR #2410)
* Bump object-path from 0.11.5 to 0.11.7 in /frontend (from PR #2408)
* Bump whitenoise from 5.2.0 to 5.3.0 (from PR #2407)
* Bump dockerflow from 2020.10.0 to 2021.7.0 (from PR #2405)
* Bump black from 21.6b0 to 21.8b0 (from PR #2404)
* Bump sphinx from 4.1.0 to 4.1.2 (from PR #2403)
* Bump node from 16.6.1-slim to 16.8.0-slim in /docker (from PR #2402)
* Bump python from 3.9.6-slim to 3.9.7-slim in /docker (from PR #2401)
* Bump tar from 6.1.3 to 6.1.11 in /frontend (from PR #2399)
> Updates 20210910

- docker/Dockerfile
* Bump node from 16.8.0-slim to 16.9.0-slim in /docker (from PR #2413)
* Bump python from 3.9.6-slim to 3.9.7-slim in /docker (from PR #2401)
> Updates 20210910 2

- docker-compose.yml
This forces the use of linux/amd64 for docker images. People who are
using m1 Macs will now be forced to emulate linux/amd64. I figured I'd
try this out now since it's the easier fix.
Docker has a "known issues" here:
https://docs.docker.com/desktop/mac/apple-silicon/#known-issues
We use inotify in a couple of places. If it turns into a problem, we can
undo this change and try something different
> bug 1731412: force linux/amd64 platform for docker images

- eliot-service/eliot/downloader.py
- eliot-service/eliot/librequests.py
- requirements.in
- requirements.txt
The `session_with_retries()` we had would create a requests `Session`
instance that used an `HTTPAdapter` that had a default timeout. It would
also create a Retry instance which would retry various error scenarios
of the HTTP request.
However, once the HTTP request is successfully sent, then a `Response`
object is created and returned. This `Response` object is now outside the
scope of all the error retry handling.
If the stream of HTTP response payload data pauses and exceeds the read
timeout, then a `ReadTimeout` error is thrown and the Eliot downloader
treats the attempt to fetch the sym file as an `ErrorFileNotFound`. It
should instead retry it.
This reworks all the requests scaffolding to keep the timeout code we
had but also cover the case where a network error when reading the HTTP …
> bug 1739202: rework requests wrappers to handle content errors

- docs/symbolication.rst
The note had the wrong uri path. This fixes it.
> Fix symbolication docs note

- eliot-service/eliot/libmarkus.py
- eliot-service/eliot/symbolicate_resource.py
- eliot-service/tests/test_symbolicate_resource.py
This allows us to track proxied and unproxied requests so we know when
to remove the proxy bits.
> bug 1739447: emit incr when TeckenProxied header exists and is 1

- docs/symbolication.rst
This clarifies the docs around which symbolication api service is
deprecated and which to switch to.
> bug 1739449: clarify symbolication api deprecation docs

- Makefile
- requirements.in
- requirements.txt
- Fix rebuildreqs and updatereqs to not run dependent containers
- Upgrade Django to 2.2.25
> upgrade django

- systemtests/bin/symbolicate.py
This updates the symbolicate script to use the new symbolication service
and also changes the default to version 5.
> Update symbolicate script to use new service

- Makefile
- docs/configuration.rst
- requirements.in
- requirements.txt
This updates to Everett 3.0.0 and updates the configuration documentation to use Everett's new Sphinx directives.
> Update to Everett 3.0.0

- .readthedocs.yaml
- docs/conf.py
- readthedocs.yml
It's hard to tell why the docs aren't building.
This reworks the readthedocs configuration file to match version 2 of their configuration spec.
> bug 1750048: fix readthedocs builds

- .readthedocs.yaml
We're compiling the `requirements.txt` file using Python 3.9 and
jsonschema requires importlib-resources with Python < 3.9 and RTD is
using Python 3.8. This fixes that.
> bug 1750048: change Python version to 3.9 for readthedocs

- tecken/tests/test_views.py
- tecken/urls.py
- tecken/views.py
This helps us verify that unhandled exceptions are sent to Sentry
in server environments.
> bug 1751458: implement broken endpoint

- Makefile
- docker-compose.yml
- docker/config/local_dev.env
- docker/config/test.env
- docker/images/fakesentry/Dockerfile
- requirements.in
- requirements.txt
- tecken/settings.py
- tecken/wsgi.py
This adds Kent as a fake Sentry service and switches the Tecken webapp over to use the sentry-sdk.
Note: This doesn't update the Tecken webapp frontend which is using raven-js. I'll do that in a separate PR.
> bug 1671188: switch tecken from raven to sentry-sdk

- bin/build_frontend.sh
- frontend/package.json
- frontend/src/App.js
- frontend/yarn.lock
I confirmed that it's not currently in use. Rather than switch Raven out
for `sentry/@browser`, I'm going to remove it for now and if we need it we
can implement `sentry/@browser` then.
> bug 1671188: remove raven-js from Tecken webapp

- bin/run_eliot_disk_manager.sh
- eliot-service/eliot/cache_manager.py
This adjusts the run script for the eliot disk cache manager. The
thinking is that in the case the disk cache manager hits an unhandled
exception, the process will send errors to sentry and then die. Without
a running disk cache manager, the node's cache will fill up and the
node's performance will degrade significantly and maybe die.
Maybe the errors are ephemeral? Maybe the errors are recoverable?
This adjusts the run script to run the disk cache manager process in a
loop. If the disk cache manager dies, then the loop will pause for a
minute and start the disk cache manager again. If the error was
ephemeral or recoverable, the disk cache manager will take stock of the
cache, clean it up, and continue functioning. If the error was not
ephemeral or recoverable (a code bug, perhaps), then …
> bug 1699776: adjust how disk cache manager is run

- Makefile
- docker/Dockerfile
- docker/images/fakesentry/Dockerfile
This fixes the problem where pip-tools doesn't work with pip 22. When
there's a pip-tools update, we can update to that and drop this
restriction.
> bug 1753051: restrict pip < 22

- docker/Dockerfile
- requirements.in
- requirements.txt
pip-tools 6.5.0 fixes the issue that required us to restrict pip to <22.
This updates pip-tools to 6.5.0 and removes the restriction.
> bug 1753051: update pip-tools to 6.5.0 and remove pip restriction

- requirements.in
- requirements.txt
- tecken/pytest.ini
This updates dockerflow to 2022.1.0 which fixes one of the warnings we
were ignoring in the pytest configuration.
> Update dockerflow to 2022.1.0

- docs/upload.rst
The upload docs weren't clear on the structure of the symbols ZIP file.
This improves that and includes an example.
> Improve upload docs

- eliot-service/eliot/symbolicate_resource.py
This adds some validation for "jobs" value. We should switch to
validating based on a schema, but this is a quick fix for now.
> bug 1740560: validate jobs value

- .circleci/config.yml
- Makefile
- bin/circleci_push.sh
- bin/run_test.sh
This swaps out the deprecated ci-docker-bases image for cimg/base:2022.02 image for running CI environment.
This also:
* updates circleci configuration
* fixes yamllint issues and removes some duplicate yaml
* parallelizes the jobs
> bug 1758712: migrate to cimg/base:2022.02 for ci

- docker-compose.yml
- docker/Dockerfile
- docs/configuration.rst
This variable was used to add the sentry dsn to the js code. We don't do
that anymore so we can remove it.
> bug 1671188: remove SENTRY_PUBLIC_DSN bits

- bin/run_migrations.sh
- bin/sentry-wrap.py
This adds a script for running migrations for Tecken such that it's
wrapped in sentry-error-reporting goodness.
> bug 1753278: add sentry-wrap.py and run_migrations.sh scripts

- bin/run_test.sh
- pytest.ini
The tecken pytest.ini needs to be up a level so it's not embedded in the
tecken code.
With eliot, we did this differently where eliot-service/ is a top-level
for all the service bits, but is not itself a python module.
> bug 1667211: move tecken test config up a level

- tecken/settings.py
The id is a str--not an int. This fixes that.
Previously, this configuration item was a SecretValue for server environments and an IntValue in the local dev environment:
https://github.com/mozilla-services/tecken/blame/eb55264be41e7315858adc8120949d95ed267db5/tecken/settings.py#L641
> bug 1667211: fix OIDC_RP_CLIENT_ID configuration parsing

- tecken/settings.py
If we use json.loads, it doesn't work with single quotes. This changes
the dict parsing to use ast.literal_eval which works better.
> bug 1667211: fix config dict value parsing

- docker/images/fakesentry/Dockerfile
fix bug [1762056](https://bugzilla.mozilla.org/show_bug.cgi?id=1762056) 
Kent 0.4.0 became incompatible with Flask's yesterday release 2.1.0, breaking fakesentry docker image build. This fixes fakesentry image build by updating Kent to 0.4.1. 
Tests:
`make test`, `make build` and `make run` from a fresh clone
> fix bug 1762056: update kent to 0.4.1 for compatibility w/ new flask 2.1.0

- frontend/src/Common.js
- frontend/src/Files.js
- tecken/api/forms.py
- tecken/api/urls.py
- tecken/api/views.py
- tecken/tests/test_api.py
Related to bug 1668371 (doesn't fix it)
This change addresses the slowness on the File Uploads page by splitting that page into two different components that will load asynchronously (note the UI doesn't change, only how the components load): 
* "Files", which populates a table with a list of files and 
* "FilesAggregates", which provides total count, avg size and avg upload time. 
Local tests have indicated usability will increase since users will be able to visualize the list of files quicker while the Aggregates part, slower to fetch, loads in parallel.
This change was also done to make further work on optimizing performance of that page easier, by allowing us to tweak the distinct components individually.
> bug 1668371: Async fetch Files and Aggregates

- frontend/src/Uploads.js
- tecken/api/urls.py
- tecken/api/views.py
- tecken/tests/test_api.py
Related to bug 1668371 (greatly alleviates its symptoms but doesn't quite fix it)
This change addresses the slowness on the Uploads page by splitting that page into two different components that will load asynchronously (the UI doesn't change, only how the components load): 
- "Uploads", which populates a table with a list of uploads 
- "Aggregates", which provides the aggregated metrics on the bottom of the page
I tested the different functionalities of the page such as page navigation, filters (including "Your Uploads") and the "New Uploads" button that refreshes the page when clicked.
> Bug 1668371 async fetch uploads

- docker/config/local_dev.env
- tecken/base/symboldownloader.py
- tecken/settings.py
- tecken/upload/utils.py
When try symbols get uploaded, the "does this exist in s3?" cache wasn't
getting invalidated, so symbol download could continue to kick up 404s.
This fixes that specific issue by adding the try symbols source to the
downloader hard-coded in the upload code. There's another bug to rewrite
how all this works and we can fix it in a more resilient way then.
To test:
1. log in and create an API token with "upload try symbols files" permission
2. create a zip file to upload
3. `curl --head http://localhost:8000/try/<debugfilename>/<debugid>/<filename>.sym`
This should return a 404 because the symbol doesn't exist.
5. upload the zip file and make sure the file got uploaded
6. `curl --head http://localhost:8000/try/<debugfilename>/<debugid>/<filename>.sym`
This should return a 200 now because the …
> bug 1758566: fix cache invalidation for try symbols

- docs/conf.py
- docs/upload.rst
This adds some documentation to the upload API encouraging people to use
the stage environment for testing symbol uploads and walks through how
to do that.
> bug 1774203: document uploading to stage

- eliot-service/eliot/app.py
- eliot-service/tests/test_sentry.py
This fixes Eliot so that Sentry is capturing errors from
sentry_sdk.capture_exception() rather than from the LoggingIntegration
listening to LOGGER.exception.
> bug 1764569: change error capture to be explicit

- eliot-service/eliot/app.py
- eliot-service/tests/test_sentry.py
Eliot uses SentryWsgiMiddleware which assigns "generic WSGI request" as
the transaction name which is unbelievably unhelpful in the Sentry
interface.
This fixes the transaction name to be the req.path which is what other
web framework integrations do.
> bug 1764569: fix transaction name for Eliot Sentry events

- eliot-service/eliot/app.py
- eliot-service/tests/test_sentry.py
- tecken/apps.py
This pulls the sentry code together so we can comment on how we're
setting it up and it's easier to maintain going forward.
This also changes the "handled" to False to match what the
DjangoIntegration does.
> bug 1764569: minor changes to sentry code

- docker-compose.yml
I'm pretty sure we don't need this anymore since symbolic provides
wheels suitable for m1 macs now.
> bug 1743854: remove platform setting from docker-compose

- bin/run_web.sh
This doubles the gunicorn worker timeout to 600 so that it's less likely to kill a symbol upload request while it's being processed leaving files on disk.
> bug 1790808: increase gunicorn timeout to 600

- .dockerignore
- frontend/src/Common.js
- frontend/src/Uploads.js
- systemtests/bin/make-symbols-zip.py
- tecken/api/urls.py
- tecken/api/views.py
- tecken/tests/test_api.py
This does a few things to simplify the uploads page:
1. cleans up and clarify the filter form so I can remember how to use the damn thing
2. removes aggregates summary (total uploads, total upload size, average size, etc) and all the code used to generate it
3. merge the `/api/uploads/*` apis back into a single endpoint
4. change the way "total" is calculated--if there are no filters, it returns 1,000,000 a "magic big number" which is handled in the front end as "lots"; if there are filters, then it calculates the count
5. removes the 5-second check loop for new uploads and the code to support that
> bug 1796579: simplify the uploads page

- frontend/src/Files.js
- systemtests/bin/make-symbols-zip.py
- tecken/api/urls.py
- tecken/api/views.py
- tecken/tests/test_api.py
This removes the aggregates summary (count, average size, etc) from the uploads files page.
This cleans up the filter form so I can remember how to use it.
This merges all the /api/uploads/files/* back into a single view.
This changes how "total" is handled. If there are no filters, then it doesn't calculate a total and instead uses 1,000,000 which is a magic number the frontend understands as "many". If there are filters, then it'll calculate the total.
> bug 1796633: remove aggregates from "upload files" pages

- eliot-service/eliot/cache_manager.py
- eliot-service/eliot/libmarkus.py
- eliot-service/eliot/symbolicate_resource.py
- eliot-service/tests/test_cache_manager.py
- eliot-service/tests/test_symbolicate_resource.py
- systemtests/bin/list-firefox-symbols-zips.py
- systemtests/bin/make-stacks.py
This moves some symbolication code around to reduce duplication between the v4 and v5 views and also to change the work of the `symbolicate` method so it's operating on a list of jobs rather than a single job. This sets us up to rewrite `symbolicate` for more efficient processing.
We switched stackwalkers at the end of 2021 and the new one emits nulls rather than omitting the field altogether. This updates `make-stacks.py` to account for nulls better.
> bug 1793984: clean up symbolication code

- bin/run_eliot_web.sh
This changes the gunicorn configuration to use max requests at 10,000 and jitter at 1,000 so we have fresh workers.
> bug 1793984: add max requests and jitter

- eliot-service/eliot/libsymbolic.py
- eliot-service/eliot/symbolicate_resource.py
- eliot-service/tests/test_libsymbolic.py
Previously, ParseSymFileError didn't include an exception message so debugging these was tricky because you knew there was an error, but it didn't include enough detail as to why.
This also fixes the handling cade to use logger.exception rather than logger.error so we get a traceback which helps debug issues.
> bug 1800479: fix ParseSymFileError to be more helpful

- docker/images/fakesentry/Dockerfile
This updates Kent to 1.0.0 and also fixes the Dockerfile to run Kent with tini.
> Update Kent to 1.0.0

- bin/run_eliot_web.sh
We added the gunicorn settings to the infra repo, so we don't need the stopgap hard-coded settings in this repo anymore.
> bug 1793984: remove gunicorn stopgap settings

- docker/Dockerfile
- docker/images/oidcprovider/Dockerfile
This fixes the web and oidcprovider services.
The frontend service uses node-14.17.6-slim which is based on stretch and doesn't have tini available. We'll have to wait to fix that until we update node. :cry:
> bug 1819191: use tini for services

- docker/config/test.env
- tecken/base/decorators.py
- tecken/settings.py
- tecken/tests/test_decorators.py
- tecken/upload/views.py
This drops `UPLOAD_TEMPDIR_PREFIX` for `UPLOAD_TEMPDIR` which is an absolute path to a directory to use for building temporary workspaces for handling symbol uploads.
While doing this, I moved the `make_tempdir` decorator closer to the only place it's used in the codebase.
This requires a configuration change in the infrastructure code before landing.
> bug 1821063: fix temporary directory usage

- Procfile
- bin/entrypoint.sh
- tecken/settings.py
- tecken/tests/test_upload.py
- tecken/upload/management/commands/remove_orphaned_files.py
When a gunicorn worker is handling a symbol upload request and it takes too long, gunicorn will kill the worker off orphaning the workspace the worker was using. This causes the disk to fill up and then the node to fail.
This fixes that by adding a "disk manager" process that wakes up periodically to remove files that have been around too long and have likely been orphaned.
> bug 1817902: add orphaned files removal

- bin/entrypoint.sh
- bin/run_web.sh
- bin/run_web_disk_manager.sh
- docker/config/local_dev.env
- tecken/settings.py
- tecken/tests/test_upload.py
- tecken/upload/management/commands/remove_orphaned_files.py
This redoes the output for remove_orphaned_files so it's logged rather than written to stdout/stderr. In order to test that, I had to fix how logging was configured in tecken so that it all went through the root--that way I can use caplog in the tests.
While doing that, I fixed honcho to not prepend prefixes to log lines and I added the "processname" (as set by the run scripts) to the log metadata.
> bug 1817902: redo remove_orphaned_files output; fix logging issues

- eliot-service/eliot/symbolicate_resource.py
- eliot-service/tests/test_symbolicate_resource.py
This fixes the debug timings for symbolication to split up "download", "parse", and "save" into separate timings. This will make it easier to discover performance issues.
> bug 1828542: fix debug timings for symbolication

- systemtests/README.rst
- systemtests/bin/upload-symbols.py
This increases the sleep after hitting rate-limiting from 10 to 15. That makes the test run longer, but it decreases the number of 429s hit and decreases the likelihood you hit 5 in a row causing the test to exit.
This improves the system test docs by adding information about api tokens.
> Change sleep to 15; improve docs

- tecken/base/admin.py
- tecken/base/templates/admin/site_status.html
This adds some additional tables to the row counts listing so we can see growth in those tables over time. Also, since it takes a while to count rows, this keeps track of how long it took to do a count for each table.
> Add additional tables and timings to site_status admin page

- systemtests/bin/list-firefox-symbols-zips.py
This fixes the list-firefox-symbols-zips script to handle changes they made in firefox ci where they purged a bunch of symbols zip files, but didn't update the expiry in the artifact records.
This skips tasks that are more than 3 months old (1 year - 9 months) and adds skipping for artifacts that have expired as well.
> bug 1832823: fix list-firefox-symbols-zips

- tecken/base/symboldownloader.py
- tecken/tests/test_symboldownloader.py
get_symbol_stream is from the old symbolication API code and we don't need it any more.
> bug 1739449: remove get_symbol_stream

- frontend/src/Common.js
- frontend/src/Files.js
- frontend/src/Uploads.js
- tecken/api/views.py
This changes the uploads and files pages to default to looking at only the last 30 days. This radically reduces how much time it takes to render the pages and gets us around the "omg--it's so slow" problem.
> bug 1814436: default uploads and files pages to last 30 days

- bin/run_test.sh
- frontend/src/Home.js
- tecken/api/views.py
- tecken/tests/test_api.py
This does a few things to reduce the work done by the stats view which is called by the home page:
1. removes the "missing symbols" stats--we're removing missing symbols bookkeeping, so we can remove this now
2. removes the uploaded files counts--I'm not sure this really means anything and comparing two uploaded files counts numbers doesn't really tell us anything
3. removes some other things that were generated by the stats view but weren't used in the frontend--this was extra work being done with no value
> bug 1840655: reduce home page stats

- requirements.in
- requirements.txt
* Update Django to 3.2.20
* Bump werkzeug from 2.3.3 to 2.3.4 (from PR #2745)
* Bump exceptiongroup from 1.1.0 to 1.1.1 (from PR #2744)
> Updates 20230712

- systemtests/bin/make-symbols-zip.py
- systemtests/bin/upload-symbols-by-download.py
- systemtests/bin/upload-symbols.py
Some symbols zip files are big, so the timeout values should match the timeout values we're using.
> Fix timeout values for systemtests scripts

- docker/config/local_dev.env
- docker/config/test.env
- docs/upload.rst
- frontend/src/UploadNow.js
- pytest.ini
- systemtests/data/sym_files_to_download.csv
- tecken/api/views.py
- tecken/base/admin.py
- tecken/base/symboldownloader.py
- tecken/libdockerflow.py
- tecken/settings.py
- tecken/storage.py
- tecken/tests/conftest.py
- tecken/tests/test_api.py
- tecken/tests/test_download.py
- tecken/tests/test_libdockerflow.py
- tecken/tests/test_storage.py
- tecken/tests/test_symboldownloader.py
- tecken/tests/test_upload.py
- tecken/tests/test_views.py
- tecken/upload/views.py
This is a big PR because it covers several tangled things:
1. removes all the `UPLOAD_URL_EXCEPTIONS` stuff which tied specific accounts to specific private buckets via configuration
2. removes all the private bucket support
3. reworks the tests removing the bulk of the mocking and instead relying on manipulating the localstack fake s3 service the tests run with (bug 1834626)
> bug 1843356, 1834626: remove support for private buckets

- systemtests/bin/download-sym-files.py
This fixes `download-sym-file.py` so it logs redirects and the final status code. This makes it clearer when the download API that's being tested is returning the correct values.
This also fixes the timeout for `download-sym-files.py` script.
Previous unhelpful output:
```
Working on https://symbols.stage.mozaws.net/cryptsp.pdb/410A559EA9162634084E228ADDEE69A91/cryptsp.sym ...
Elapsed time: timing download_time 2.33s
```
New much more informative output:
```
Working on https://symbols.stage.mozaws.net/cryptsp.pdb/410A559EA9162634084E228ADDEE69A91/cryptsp.sym ...
>>> redirect: https://symbols.stage.mozaws.net/cryptsp.pdb/410A559EA9162634084E228ADDEE69A91/cryptsp.sym
>>> final: https://s3.us-west-2.amazonaws.com/org.mozilla.crash-stats.symbols-public/v1/cryptsp.pdb/410A559EA9162634084E228ADD …
```
> bug 1843356: improve download-sym-files.py script

- tecken/base/symboldownloader.py
This fixes `check_url_head` to not log an error for HTTP 403. We get an expected HTTP 403 when the S3 bucket doesn't have a symbol file.
> bug 1843356: don't log an error for http 403 in check_url_head

- frontend/src/Common.js
If an upload is interrupted, Tecken doesn't end up with a correct count of the number of files in the upload. It only knows about the files it has processed so far or was in the process of processing. This fixes some language in the UI around that.
If an upload is interrupted, when you go to look at an upload file view for a file in the upload, it displays some stats about the upload including a `DisplayIncompleteRatio` section which required data that wasn't in the API response. Because Tecken doesn't know how many files were in the upload, I decided to just nix the `DisplayIncompleteRatio` section altogether because the information it was trying to render wasn't meaningful.
> bug 1847937: fix upload file view for files in incomplete uploads

- frontend/src/Uploads.js
This adds an "upload-by-download" column to the uploads view so it's easy to see which were upload-by-download and which weren't.
> bug 1847930: add UBD column

- tecken/base/symboldownloader.py
- tecken/tests/test_symboldownloader.py
This fixes the download API to url quote paths before doing an HTTP HEAD. This correctly handles characters like `+` where it needs to be quoted. Otherwise we get back an HTTP 404 from AWS S3 even if the file is there.
> bug 1848567: fix download API for symbols with special characters

- docker/Dockerfile
This adds --no-deps to the pip install flags for building the tecken app image. This prevents pip from installing dependencies not explicitly listed in the requirements.txt file.
> Add --no-deps to pip install for image building

- tecken/tests/test_tokens.py
- tecken/tests/test_useradmin.py
- tecken/tokens/management/__init__.py
- tecken/tokens/management/commands/__init__.py
- tecken/tokens/management/commands/createtoken.py
This will aid development since it makes it possible to create API tokens from the command line.
```
$ docker compose run --rm web bash python manage.py createtoken EMAIL
```
```
$ docker compose run --rm web bash python manage.py createtoken EMAIL TOKENKEY
```
> bug 1851809: implement createtoken command

- tecken/upload/admin.py
- tecken/upload/management/commands/generate_fake_data.py
This fixes the `FileUpload` admin which wasn't usable in prod before because it'd create a drop-down for upload which had ... 300k items in it. We'll never want to change that field value, so now it's readonly.
This adds a fake data generator that's kind of terrible, but good enough for now and something we can improve over time as needs arise.
> bug 1746940: fix FileUpload admin; add fake data generator

- requirements.in
- requirements.txt
- tecken/settings.py
- tecken/upload/admin.py
This switches pagination in the Django admin for the Upload and FileUpload models to django-admin-cursor-paginator which doesn't do limit/offset stuff which is rough when the tables are big.
> bug 1851909: switch to django-admin-cursor-paginator

- docs/download.rst
- tecken/download/urls.py
- tecken/download/views.py
- tecken/tests/test_download.py
This reworks the download API to support `/code_file/code_id/sym_file` urls. If it sees this, it'll look up `code_file` / `code_id` in the fileupload records. If it finds one, it'll return an HTTP 302 with the correct `debug_filename` and `debug_id`.
This works for both HEAD and GET requests.
This updates the download API documentation as well.
> bug 1746940: rework download API to support /code_file/code_id/sym_file

- docs/upload.rst
- frontend/src/Tokens.js
- tecken/tests/test_tokens.py
- tecken/tokens/middleware.py
This adds support for appending a "-" and some text as a comment to a token. If you have multiple tokens with different permissions, this makes it easier to keep them straight.
For example, if I had an API token with "upload try symbols" permission, I could comment it like this:
```
E468C3D4BBDA43DEBC0B856983895835-uploadtry
```
> bug 1774217: add support for token comments

- tecken/api/views.py
- tecken/tests/test_api.py
- tecken/upload/models.py
This fixes the url value in the syminfo API for try symbols. Now it points to the right place.
> bug 1854206: fix url for try symbols

- tecken/upload/utils.py
This fixes the unboundlocalerror when creating the SymParseError. It also fixes the memory usage issue by switching to readline instead of readlines.
> bug 1854219: fix unboundlocalerror in extract_sym_header_data

- bin/build_frontend.sh
- bin/cleanup.sh
- tecken/tests/test_upload.py
- tecken/upload/management/commands/clearuploads.py
Adds a bin/cleanup.sh script we can use to run all the cleanup commands. This also renames cleanse_upload to clearuploads to be more like the existing clearsessions command.
> bug 1855483: add cleanup.sh script

- tecken/upload/admin.py
upload_id already works and we don't need the additional upload_id method which forces the Django admin to additionally pull each upload record one-by-one.
> bug 1851909: remove unneeded upload_id method

- bin/download-sym.py
This change strips of the `.pdb` suffix of the debug filename if it exists before adding the `.sym` extension. For extra flexibilty it also supports overriding the sym file name manually. I tested this locally for a Windows symfile with these two commands, and both downloaded the symbols:
```
bin/download-sym.py sym 69425277EC5145FFAB3266EB4C20384D1 nvcuda.pdb
bin/download-sym.py sym 69425277EC5145FFAB3266EB4C20384D1 nvcuda.pdb nvcuda.sym
```
> bug 1847579: Make download-sym.py work for Windows modules.

- docker/config/local_dev.env
This makes it possible to open a shell in a dev container in VS Code. The shell for the `app` user [otherwise defaults to `nologin`](https://github.com/mozilla-services/tecken/blob/aba9574708b08e1ffe80a6ea34cc89d1220ed2e4/docker/Dockerfile#L27-L29), which i not a useful shell.
We probably also want this fix for other projects.
> Set SHELL env variable in local development containers to bash.

- requirements.in
- requirements.txt
@smarnach went through the release notes for Django comparing to the previously installed version and reviewed all the major changes and the extent to which we were using those Django features. He didn't find any changes strictly necessary, though he did find that we could upgrade our Postgres DB library `psycopg2` to version 3.
> bug-1809727: upgrade django to 4.2.7 LTS

- docker/Dockerfile
I had problems with using Debian 12 (aka bookworm) with Socorro where bookworm has a different version of glibc than bullseye does in [bug 1853662](https://bugzilla.mozilla.org/show_bug.cgi?id=1853662). Thus Socorro uses bullseye and we should probably use bullseye across all the things we maintain.
I theorize this might fix the issue where honcho is failing with a `RuntimeError` trying to start threads in Tecken stage. I hypothesize that Python compiled in bookworm is compiled against a newer glibc (or some other system library) and that doesn't work on the hosts Tecken is running on. So when honcho starts a thread, it fails with a `RuntimeError`.
If the theory holds true, the problem will go away if we downgrade to Debian 11. Even if it doesn't, we'll switch Tecken to bullseye which is …
> bug-1743835: switch python image from bookworm to bullseye

- tecken/settings.py
This drops the cutoff from 60 minutes which kept orphaned files way too long causing an instance to have disk-full problems for over an hour to 15 minutes which will allow instances to recover more quickly.
15 minutes far exceeds the 6 minute timeout for HTTP request handling, so files that are still around after 15 minutes are certainly orphaned.
---
The Tecken webapp handles upload API requests. These requests can take a very long time to handle. If the request exceeds 6 minutes, it's possible that the gunicorn worker serving the request will get killed off. If that happens, then the symbols files on disk that the upload API handler was processing get orphaned and remain on disk. The disk is finite, so after enough of these events, then the instance has no more disk left and starts …
> bug-1863007: change UPLOAD_TEMPDIR_ORPHANS_CUTOFF to 15 minutes

- bin/run_web_disk_manager.sh
- bin/sentry-wrap.py
- tecken/tests/test_upload.py
- tecken/upload/management/commands/remove_orphaned_files.py
- tecken/upload/utils.py
- bug-1853962: improve disk cache manager error handling
- bug-1853962: change UPLOAD_TEMPDIR does not exist into non-error
This does a few things to make the disk manager more resilient:
1. removes the daemon functionality: the script runs in a loop already, so we don't need the additional daemon loop in the command
2. wrap the `remove_orphaned_files` command in `sentry-wrap`: this will make sure we get errors sent to sentry
3. add a timeout for the command: we probably don't need a timeout, but this adds one anyway so if it takes longer than 60 seconds to run, `sentry-wrap` will kill it and send an error to Sentry
4. adds a `--verbose` to `sentry-wrap`: this makes it so that `sentry-wrap` doesn't spit out non-essential output unless asked to
5. fix output: this removes non-error output …
> bug-1853962: improve disk manager resilience

- bin/run_web.sh
- docker/config/local_dev.env
- tecken/gunicornhooks.py
- tecken/tests/test_gunicornhooks.py
This uses gunicorn server hooks to emit a tecken.gunicorn_worker_abort incr when the gunicorn manager terminates a gunicorn worker because it's exceeded the timeout. This happens when it's taking too long to process an upload API request.
The test for this is contrived at best and only verifies that the metric we expect is emitted.
It's difficult to do a real test because that requires Tecken to be running with gunicorn and for a gunicorn worker to exceed the timeout such that the gunicorn manager kills the process. We can manually test it using the steps in this blog post:
https://bluesock.org/~willkg/blog/mozilla/tecken_worker_exit.html
When the Gunicorn manager sends a SIGABRT to the Gunicorn worker, we'll see the metric emitted:
```
tecken-web-1           | INFO 2023-11-30 …
```
> bug-1847235: emit tecken.gunicorn_worker_abort incr on timeout

- .github/CODEOWNERS
This adds a CODEOWNERS file which adds a default rule covering the
entire repository with the obs-team.
> bug-1868132: add CODEOWNERS file

- tecken/base/admin.py
- tecken/settings.py
Because:
* There is application-level branching logic required[1], depending on which cloud service provider we are using.
This commit:
* Creates a new env var, CLOUD_SERVICE_PROVIDER, defaulting to "AWS"
* Adds this env var to the Settings section in the Django /admin/sitestatus page.
[1]: For example, markus needs to add an additional tag in GCP that is already tagged by Telegraf in AWS. Another example is that we will need different storage backend setup code depending on if we're using AWS S3 or GCP GCS.
Tecken config docs:
Django admin settings page:
I have separately added a line item for the [Tecken GCP migration plan](https://docs.google.com/document/d/1tLoGhMJQrP1m6A5H3D5zElNbTHQ9_vzYbOE9QnrxLUc/edit?usp=sharing) to set this env var to "GCP" as part of setting up the GCP stage …
> bug-1835888: initialize CLOUD_SERVICE_PROVIDER env var

- docker/config/test.env
- tecken/base/symboldownloader.py
- tecken/settings.py
The results of `get_last_modified()` are cached in Redis, so we can't use datetime objects here, since they can't be serialized by MessagePack. We did not catch this mistake in the tests because the tests used to use an in-memory cache without serialization. This change also makes the tests use an actual Redis container in the tests.
> bug-1868790: Return Unix timestamps from get_last_modified().

- docker-compose.yml
see also https://github.com/mozilla-services/eliot/pull/113
per https://github.com/mozilla-services/tecken/pull/2857/files#r1430382049
> ```
>  "shutdownAction": "none",
> ```
> [biancadanforth](https://github.com/biancadanforth) [Dec 18, 2023](https://github.com/mozilla-services/tecken/pull/2857/files#r1430382049):
>  This is what prevents the devcontainer from shutting down when we close out of VS Code IIUC.
with devcontainer and its docker-compose dependencies running even when vscode isn't open, ports conflict between tecken, eliot, and socorro, so this PR makes the exposed ports configurable via environment variables, which can be set in `.env` in each project to avoid overlap.
> Make ports exposed in docker compose configurable

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .vscode/extensions.json
- docs/dev.rst
This PR adds a dev container configuration for VS Code. Features:
* All dependencies are installed in the dev container, so IntelliSense fully works, and type checking will also work once we add type annotations.
* Allows running the tests using [VS Code's Python test browser](https://code.visualstudio.com/docs/python/testing), which makes running and debugging tests really convenient. (This is the main reason to use a container instead of a virtualenv in the first place.)
* Sets up Black as the default Python formatter. We can consider adding a setting to automatically format Python code on save.
I'm not really an expert on VS Code, so it's possible there are better ways of setting this up. This configuration works well for me, though, and it might be useful for others as well.
> Add VS Code dev container configuration.

- .devcontainer/Dockerfile
This fixes a problem introduced in #2872.
If the user or group id is 1000, this will still create a user or group with the same id as the existing `vscode` user or group. This can in general be a bit confusing, but I don't think it will cause actual problems in the dev container.
The existing `vscode` user has a home directory in the container, and owns some random stuff in `/usr/local` (probably unintentionally).
> Don't error out when building the dev container for uid/gid 1000.

- bin/upload-sym.py
This fixes a bug introduced in September 2023 in 23daea485d, where I fixed the code to generate the right sym_file filename for Windows, but broke it for Linux/macOS. This fixes Linux/macOS.
For Windows, the sym_file filename involves taking the debug file, dropping `.pdb`, and adding `.sym`. e.g. `libxul.pdb` -> `libxul.sym`.
For Linux/macOS, the sym_file filename involves adding `.sym` to the end of the debug file. e.g. `glxtrace.so` -> `glxtrace.so.sym` and `XUL` -> `XUL.sym`.
> Fix upload-sym.py sym_file generation

- .circleci/config.yml
- pyproject.toml
Because:
* We have standardized on tags starting with v
This commit:
* Ensures the `main` job for CI is run for all branches and only tags starting with v, instead of all branches and all tags.
* Updates our `release.py` config to pass in the new tag format when creating the tag as part of a release.
Notes:
* I didn't update any docs, since I didn't see any mentions of the tag format in either the `/docs` directory in the repo or on the [Tecken page in Confluence](https://mozilla-hub.atlassian.net/wiki/spaces/CS1/pages/178061663/Symbols+aka+Tecken)[1]. Please let me know if I missed anywhere.
* I've added two new [tag protection rules](https://github.com/mozilla-services/tecken/settings/tag_protection) in the repo based on the [match patterns used by Eliot for its `build-and-push` GitHub …
> bug-1835880: switch tag pattern to vYYYY.MM.DD[-N]

- requirements.in
- requirements.txt
- tecken/base/symboldownloader.py
- tecken/download/views.py
- tecken/settings.py
- tecken/tests/test_upload_utils.py
- tecken/upload/utils.py
Because:
* This library is no longer maintained.
* The minimal caching it was doing doesn't warrant the continued maintenance burden (in particular the Redis caching backend).
This commit:
* Removes uses of the library in the source code.
* Removes it from our list of dependencies.
* Fixes tests for the affected functions.
Note: This PR does not remove the Redis config, as per [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1759554#c7) in the bug, we want to monitor some metrics in prod first before proceeding with that step.
> bug-1759554: remove django-cache-memoize

- docker-compose.yml
Because:
* This service runs on the AMD64 platform instead of ARM on some Macs (e.g. my M1).
* Therefore it runs under emulation and is slower and fails the healthcheck added in PR #2880.
This commit:
* Increases the interval, timeout and retries, so that the devcontainer service starts up without issue on such OSes.
> increase interval, timeout and retries on oidcprovider service

- docs/Makefile
- docs/conf.py
- docs/dev.rst
This fixes restructuredText syntax issues with dev.rst preventing it from compiling.
Before this change, running `make docs` kicked up a bunch of errors:
```
/app/docs/dev.rst:109: ERROR: Error in "code-block" directive:
maximum 1 argument(s) allowed, 4 supplied.
.. code-block:: shell
$ make devcontainerbuild
/app/docs/dev.rst:143: ERROR: Error in "code-block" directive:
maximum 1 argument(s) allowed, 7 supplied.
.. code-block:: shell
EXPOSE_TECKEN_PORT=8200
EXPOSE_LOCALSTACK_PORT=4567
EXPOSE_SENTRY_PORT=8290
EXPOSE_OIDC_PORT=8280
EXPOSE_STATSD_PORT=8281
EXPOSE_GCS_EMULATOR_PORT=4443
/app/docs/dev.rst:154: ERROR: Error in "code-block" directive:
maximum 1 argument(s) allowed, 4 supplied.
.. code-block:: shell
$ make devcontainer
/app/docs/dev.rst:315: WARNING: Title underline too short. …
```
> Fix syntax problems with dev.rst

- Makefile
This reduces the copious output of backing services when running `make run`.
To test:
1. `docker compose stop` to reset everything
2. `./slick.sh` to start up backing services and set state for everything
3. `make run` to start up web, fakesentry, and frontend services
Expected: Output for web, fakesentry, and frontend services appears in stdout, but output for backing services (e.g. statsd and friends) does not.
> bug 1877534: mark backing services with --no-attach

- docker/images/fakesentry/Dockerfile
This upgrades Kent to 1.2.0 to pick up fixes to logging and other things. That will quell the logging from the healthcheck hitting / every second.
This also updates the Dockerfile to use the same base image Tecken does.
> bug-1877534: upgrade Kent to 1.2.0

- docker-compose.yml
This duplicates the `test-ci` configuration into the `test` configuration, thereby avoiding the need to recursively resolve `extends` declarations. This works around https://github.com/docker/compose/issues/11413. We can revert this once the fix is available everywhere.
> bug-1877411: Work around race condition in compose-go.

- requirements.in
- requirements.txt
4.2.8 release notes: https://docs.djangoproject.com/en/5.0/releases/4.2.8/
4.2.9 release notes: https://docs.djangoproject.com/en/5.0/releases/4.2.9/
4.2.10 release notes: https://docs.djangoproject.com/en/5.0/releases/4.2.10/
Generally, this just upgrades the version we're using, but shouldn't affect Tecken at all since we don't use most of the things that changed.
> obs-125: update django to 4.2.10

- requirements.in
- requirements.txt
- systemtests/README.rst
- systemtests/bin/download_sym_files.py
- systemtests/bin/list_firefox_symbols_zips.py
- systemtests/bin/setup_download_tests.py
- systemtests/bin/setup_upload_tests.py
- systemtests/bin/upload_symbols.py
- systemtests/bin/upload_symbols_by_download.py
- systemtests/setup_tests.py
- systemtests/systemtestslib/utils.py
- systemtests/test_env.py
`systemtestslib/utils.py`: Change `get_sym_files` to only emit files where `completed_at` is non-None so we don't get a 404 when trying to download them.
`systemtestslib/utils.py`: Shuffle around parameters in `get_sym_files` and callers.
`systemtestslib/utils.py`: Optimize `get_sym_files` for the case where someone uploaded a ton of try symbols recently--this will move through the pages faster reducing the number of GET requests.
`test_env.py`: Converts integer values to bools for flags, tweaks the output code, and improves a comment about the bad token test. This also adjusts the bad token test to make sure it uses a zip file that's greater than 120kb which we think we need to trigger the situation the bad token test tests.
`bin/setup_upload_tests.py`:
`bin/setup_download_tests.py`: …
> Systemtest fixes

- bin/sentry-wrap.py
- docker/images/fakesentry/Dockerfile
- Fix interpreter for sentry-wrap.py
- Update fakesentry to Python 3.11.9
> update fakesentry to python 3.11.9

- bin/run_migrations.sh
- bin/run_web_disk_manager.sh
- bin/sentry-wrap.py
- bin/sentry_wrap.py
- tecken/libdockerflow.py
- tecken/tests/test_sentry.py
Because:
* We want to be able to mark an error hit in `sentry_wrap.py` as "Resolved in the next release" in Sentry, but we weren't passing in the `release` in this context (see this [reference error's events](https://mozilla.sentry.io/issues/4723701783/events/?project=6700123)).
This commit:
* Passes `release` when calling `sentry_sdk.init` in `sentry_wrap.py`.
>  bug-1889200: specify release in sentry-wrap.py

- tecken/tokens/admin.py
This impproves the Token admin making it effectively like the one in Crash Stats. One nice thing is that tokens are searchable now.
To test:
1. create a token:
```
docker compose run --rm web bash python manage.py createtoken EMAIL TOKEN
```
2. run everything with `make run`
3. log in, go to the admin, go to the token manager
4. view token list
5. search tokens using email address substring
> bug-1896962: improve Token admin

- docker/images/fakesentry/Dockerfile
- requirements.in
- requirements.txt
- tecken/tests/test_sentry.py
- tecken/tests/test_upload.py
This updates sentry-sdk to 2.5.1, fillmore to 2.0.0, and kent to 2.0.0. This gets us over the big sentry-sdk API change.
kent 2.0.0 API changes: https://github.com/willkg/kent/releases/tag/v2.0.0
fillmore 2.0.0 API changes: https://github.com/willkg/fillmore/releases/tag/v2.0.0
> Update sentry-sdk, fillmore, and kent

- docker-compose.yml
The GCS emulator needs special settings to allow public downloads and retriable uploads.
Public downloads are required so we can redirect to files in the GCS emulator from the download API. They are enabled by the `-public-host` command-Line option.
Retriable uploads are used by the `Blob.upload_from_file()` method. They return a redirect in the initial request, which requires the server to know its external URL, which can be set using `-external-url`.
> bug-1827507: Fix GCS emulator settings.

- .gitignore
- Makefile
Because:
* The [Tecken docs](https://tecken.readthedocs.io/en/latest/dev.html#how-to-set-up-a-development-container-for-vs-code) suggest running this command to build the devcontainer docker container.
* The command had a cyclic dependency on the .devcontainer-build file it is intended to create, causing it to enter an infinite loop when running the command locally if the .devcontainer-build file doesn't yet exist.
This commit:
* Moves the .devcontainer-build file requirement from `make devcontainerbuild` to the `make devcontainer` command.
* adds .devcontainer-build to .gitignore
> Fix `make devcontainerbuild` command when .devcontainer-build file doesn't exist

- .github/workflows/build-and-push.yml
This workflow pushes Docker images to Google Artifact Registry for use in GCP. It will eventually replace the Circle CI workflow.
The workflow is mostly copied from Eliot, with the commands adapted to match the Circle CI workflow in this repo.
The workflow also builds a Docker image when we push to the `build-test-image` branch, to make it easier to build test images. We can remove this after the GCP migration (but we don't have to – it doesn't really hurt).
> OBS-268: Add GitHub Actions CI workflow.

- docker-compose.yml
`$EXPOSE_GCS_EMULATOR_PORT` is the port used with `localhost`, while the port used with `gcs-emulator` will always be 8001.
> Don't reference exposed port in gcs emulator options

- systemtests/bin/download_sym_files.py
- systemtests/test_env.py
Because:
* We will rely on systemtests as a primary way to validate the Tecken GCP migration.
* We were not testing HEAD requests or verifying response headers in the systemtests for the download API.
This commit:
* Tests the HTTP response for HEAD requests.
* Checks response headers for both the Tecken redirect response and the storage backend response.
* What headers to check for and their values is based largely on the specifications in the [Tecken GCP migration plan](https://docs.google.com/document/d/1tLoGhMJQrP1m6A5H3D5zElNbTHQ9_vzYbOE9QnrxLUc/edit?usp=sharing).
> bug-1906139: systemtests download API improvements

- docker-compose.yml
- docker/config/local_dev.env
- docker/images/gcs-cdn/Dockerfile
- docker/images/gcs-cdn/default.conf
- tecken/download/views.py
- tecken/ext/gcs/storage.py
- tecken/settings.py
- tecken/tests/conftest.py
- tecken/tests/test_storage_backends.py
- tecken/tests/utils.py
We want to be able to use a global load balancer in front of a GCS storage bucket, since this will drastically reduce our egress costs. This means we need to be able to configure a public URL for symbol file access that's different than the bucket URL. This PR introduces a way to configure the public URL for each bucket. It also adds an nginx container simulating a load balancer to the devstack and runs all tests using storage against that configuration.
A positive side effect is that the nginx container [makes downloading files from the host machine of the dev environment convenient again](https://github.com/mozilla-services/tecken/pull/2957#issuecomment-2218132041).
> bug-1906959: Allow GCS buckets to be behind a CDN.

- docs/upload.rst
This updates the guidance on retrying to wait 15 seconds and try again.
This also updates the discussion around which HTTP POST method to use in relation to the symbol zip archive size. We now recommend this new model where we encourage people to have symbol zip archive sizes < 2gb and they should split the archive up across multiple HTTP POSTs.
> bug-1910613: update guidance on 429s and symbols zip archive sizes

- tecken/libsym.py
- tecken/tests/test_libsym.py
This fixes sym file header parsing so it parses the entire sym file header rather than stopping after INFO CODE_ID.
While doing this, I also updated the tests for windows, mac, and linux sym file headers with dump_syms 2.3.3 output.
> bug-1907985: fix sym file header parsing

- tecken/api/views.py
- tecken/tests/test_api.py
This carries the try_symbols value from the Upload instance to the file upload upload info section in the frontend.
> bug-1910180: fix file upload upload info try_symbols value

- docs/upload.rst
- frontend/src/UploadNow.js
- tecken/api/urls.py
- tecken/api/views.py
This removes the forms from the Symbols Upload Now page. I kept the page because it contains a link to instructions on how to upload symbols using Python and curl. That seems helpful to keep.
This PR gets into a lot of react code I'm not wildly familiar with (and has no tests) so I might have missed some bits when cleaning up. However, only a handful of people in the world have the access on Mozilla Symbols to see this page, so this is pretty low risk even if we mess up.
> bug-1909013: remove upload now view forms

- frontend/src/Files.js
- tecken/api/forms.py
- tecken/api/views.py
- tecken/tests/test_api.py
Previously, you could sort of search for try uploads by searching for "try/" in the key. But you couldn't search for regular uploads.
We recently changed the key data in the model, so "try/" no longer appears in the key which breaks this flimsy filtering method.
This introduces a new upload_type filter field that lets you filter on nothing (""), try upload files ("try"), and regular upload files ("regular").
> bug-1909637: allow searching for files from regular and try symbol uploads

- tecken/tests/test_tokens.py
- tecken/tokens/middleware.py
To verify that this is working, run
```
curl -H "Auth-Token: c7c1f8cab79545b6a06bc4122f0eb3cb" -I http://localhost:3000/api/uploads/
```
substituting your auth token for the local env; the one above is the one from the slick.sh file we distribute. Verify that the Vary header includes "Auth-Token".
> bug-1910092: Add Vary: Auth-Token header for requests with a token.

- systemtests/lib/fake_data.py
- systemtests/tests/conftest.py
- systemtests/tests/test_direct_upload.py
- systemtests/tests/test_upload_by_download.py
This change makes the system test cases independent of each other. I combined the basic upload and download tests into a single test case. All other tests that need an upload simply upload a small archive first.
This change leads to a higher number of uploads when the system tests run. Since we switched to connection limiting for our Tecken deployments, this no longer leads to any rate limiting on the server side. We also introduced a lifecycle rule for our GCS buckets that expires the uploaded files early.
> bug-1909870: Make system test cases independent of each other.

- docker/Dockerfile
It's this tag:
https://hub.docker.com/layers/library/python/3.11.10-slim-bullseye/images/sha256-99010d5cbf95418c4dbaeb3be33658bc1b65c3a6324bba447424c6768728e4f7?context=explore
> Update Python 3.11.10 slim-bullseye image

- bin/upload-sym.py
Instead of uploading a single sym file at a time, I decided to fix upload-sym.py to support uploading multiple files in one upload pass. Then I used it to upload the jna symbols files just now.
It now supports:
```
bin/upload-sym.py --auth-token=xyz file1.sym file2.sym file3.sym ...
```
One nice thing you can do is use `find` or `fd` to upload a bunch of sym files in a directory regardless of where in the directory they are:
```
bin/upload-sym.py --auth-token=xyz $(find tmp/ "*.sym")
bin/upload-sym.py --auth-token=xyz $(fd ".*\.sym" tmp/)
```
> Fix upload-sym to support uploading multiple files

- .github/dependabot.yml
- docker/Dockerfile
- docs/dev.rst
While we want to upgrade Python to a newer version at some point, I don't think it's useful for depednabot to suggest this to us every week.
> Prevent dependabot from proposing Python version upgrades beyond 3.11.

- docker-compose.yml
- docker/Dockerfile
- docker/images/fakesentry/Dockerfile
- docker/images/oidcprovider/Dockerfile
- frontend/Dockerfile
- frontend/bin/run_frontend.sh
The tini process was originally added to make Docker comtainers quite properly when receiving the TERM signal on `docker compose stop`. Some containers don't react to this signal, so terminating them will hang for ten seconds before Docker Compose sends SIGKILL.
This change removes tini evertywhere while ensuring container shutdown still happens on the first signal. for some containers, I added the correct signal in `docker-compose.yml` using the `stop_signal` directive. For the frontend containers I made sure the shell script uses `exec` to start the actual main process, so there shell doesn't linger in the background to block signals. For the oidc-provider, I filed a [PR with a similar change](https://github.com/mozilla/docker-test-mozilla-django-oidc/pull/84). …
> OBS-361: Remove tini from all Docker containers.

- docs/download.rst
- docs/upload.rst
This improves the HTTP status codes, adds response headers where applicable, and adds a first-pass section on improving symbol upload success rates.
This should help users who are using the download and upload APIs know what to do in certain status code situations that were previously undocumented.
This specifies the response headers so we can write systemtests for them.
This will help people writing symbol upload jobs with a set of things they can look at to improve the likelihood those jobs finish successfully. We can hone this section over time.
For whoever reviews this, feel free to merge it if it's approved. Thank you!
> Improve upload and download API docs

- .github/workflows/manual-deployment.yml
The workflow is copied without any changes from https://github.com/mozilla-services/eliot/blob/main/.github/workflows/manual-deployment.yml.
> Add manual deployment workflow.

- tecken/ext/gcs/storage.py
https://mozilla-hub.atlassian.net/browse/OBS-463
> OBS-463: Use custom time as modification time for GCS objects if set.

- .github/workflows/release.yml
This is a lightly tested prototype for a release workflow. Creating the release can be done with a simple invocation of `gh release create`. Determining the right version tag is a bit awkward though. I wonder whether I should have reused the implementation from obs-common, instead of rewriting this in POSIX shell. This version doesn't require checking out any repos and is completely self-contained, which has advantages, too.
https://mozilla-hub.atlassian.net/browse/OBS-515
> OBS-515: Add prototype release workflow.

- docker/config/local_dev.env
We use markus to prefix all metrics with `tecken.` now, so the namespace is no longer needed. Setting an additional namespace in `STATSD_NAMESPACE` results in metrics named `mcboatface.tecken.*`. By removing the namespace we get `tecken.*` instead.
(I could only observe this when I had replaced the statsd-graphite image with Telegraf, since I didn't manage to actually see the metrics with the former image. The namespace is added on the client side, though, so it shouldn't make any difference what statsd implementation I used to test this.)
> bug 1950361: Remove statsd namespace for local development.

- tecken/settings.py
Because:
* [DB connection health checks](https://docs.djangoproject.com/en/4.2/ref/settings/#conn-health-checks) are disabled by default.
* During DB maintenance, connections are closed, and Django isn't re-establishing a connection with existing configuration during uploads.
This commit:
* Enables DB connection health checks.
> CRINGE-111: enable CONN_HEALTH_CHECKS for Django DB
